// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhgau4qqCekuFkdXuNdCSrG6ccXdQpqnw',
    appId: '1:507848086716:android:c03bb24d2439e45cce6cb9',
    messagingSenderId: '507848086716',
    projectId: 'vanavil-2c565',
    storageBucket: 'vanavil-2c565.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyamCClGZx_lQhsKt2QnvdPHYFIX3LSOc',
    appId: '1:507848086716:ios:cfb08e1d4b9b5022ce6cb9',
    messagingSenderId: '507848086716',
    projectId: 'vanavil-2c565',
    storageBucket: 'vanavil-2c565.firebasestorage.app',
    iosBundleId: 'com.example.childApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjazgSqxbRV2xfRIoqCD0D4e117XE55XI',
    appId: '1:507848086716:web:21dcc6555b3b6abcce6cb9',
    messagingSenderId: '507848086716',
    projectId: 'vanavil-2c565',
    authDomain: 'vanavil-2c565.firebaseapp.com',
    storageBucket: 'vanavil-2c565.firebasestorage.app',
  );

}